### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by j143** [j143/pcap-browser#1]
$ python app.py
Traceback (most recent call last):
  File "/workspace/pcap-browser/app.py", line 187, in <module>
    db.create_all()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 887, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 858, in _call_for_binds
    engine = self.engines[key]
             ^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 639, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by j143** [comment]
solution:

https://github.com/j143/pcap-browser/commit/c32b2642bbe4d18c0e28c2295d8f140ff4e7248c#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R199-L188
